### ISSUE TITLE
Errors out of the box

### ISSUE THREAD

**Issue by lgwapnitsky** [slackapi/Slack-Python-Onboarding-Tutorial#11]
"Created" the app using a git clone of this project. Followed instructions, and connected successfully to my url/team.  When performing any action, I get output such as:

`127.0.0.1 - - [31/May/2017 15:02:04] "POST /listening HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/slackdev/env/lib/python2.7/site-packages/flask/app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/slackdev/env/lib/python2.7/site-packages/flask/app.py", line 1991, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/slackdev/env/lib/python2.7/site-packages/flask/app.py", line 1567, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/slackdev/env/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/slackdev/env/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/slackdev/env/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/slackdev/env/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/slackdev/env/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/slackdev/Slack-Python-Onboarding-Tutorial/app.py", line 139, in hears
    return _event_handler(event_type, slack_event)
  File "/home/slackdev/Slack-Python-Onboarding-Tutorial/app.py", line 60, in _event_handler
    pyBot.update_emoji(team_id, user_id)
  File "/home/slackdev/Slack-Python-Onboarding-Tutorial/bot.py", line 168, in update_emoji
    message_obj = self.messages[team_id].get(user_id)
KeyError: u'T0G61B5K9'`

I'm running Python2 on a Ubuntu 16.04 server as a hyper-v, routing through ngrok.

This is my first attempt at using self-created bots, and python is my preferred language.

Thank you,
Larry

**Comment by nbortolotti** [comment]
same error Python2 . mac environment.

**Comment by rashkur** [comment]
pip install -r requirements.txt
